const express = require('express');
const bcrypt = require('bcryptjs');

const { setTokenCookie, requireAuth } = require('../../utils/auth');
const { User } = require('../../db/models');

const router = express.Router();

//  Sign up route
router.post('/', async (req, res) => {
    const { email, password, username } = req.body;
    //  Hash user's password and save hashed password to hashedPassword in db
    const hashedPassword = bcrypt.hashSync(password);
    //  New 'User' instance has 'username', 'email', 'hashedPassword' generated by
    //  bcryptjs and set into db
    const user = await User.create({ email, username, hashedPassword });

    const safeUser = {
        id: user.id,
        email: user.email,
        username: user.username
    };

    //  setTokenCookie() logs in user by creating JWT cookie
    await setTokenCookie(res, safeUser);

    //  res.json return user's non-sensitive info
    return res.json({ user: safeUser });
})




module.exports = router;
